--
-- PostgreSQL database dump
--

\restrict LU7chLBYmqEboSvJvFvELmVoou81fjQCBJa0UgLu51b1Qr5xpqC11LWZWmqAOQC

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    address character varying(255),
    city character varying(255),
    country character varying(255),
    latitude double precision,
    longitude double precision,
    postal_code integer,
    property_id character varying(255)
);


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.amenities (
    id bigint NOT NULL,
    icon character varying(255),
    name character varying(255),
    category_id bigint
);


--
-- Name: amenities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.amenities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.amenities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: amenity_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.amenity_categories (
    id bigint NOT NULL,
    title character varying(255) NOT NULL
);


--
-- Name: amenity_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.amenity_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.amenity_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: availabilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.availabilities (
    id bigint NOT NULL,
    end_date date,
    start_date date,
    property_id character varying(255)
);


--
-- Name: availabilities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.availabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.availabilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    created_at timestamp without time zone NOT NULL,
    long_stay_discount_percent integer,
    negotiation_expires_at timestamp without time zone,
    on_chain_tx_hash character varying(255),
    property_id character varying(255),
    requested_negotiation_percent integer,
    status character varying(50) NOT NULL,
    total_price double precision,
    updated_at timestamp without time zone,
    user_id bigint NOT NULL
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_logs (
    id bigint NOT NULL,
    level smallint,
    message character varying(255),
    "timestamp" timestamp(6) without time zone,
    notification_id character varying(255),
    CONSTRAINT notification_logs_level_check CHECK (((level >= 0) AND (level <= 2)))
);


--
-- Name: notification_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id character varying(255) NOT NULL,
    channel smallint,
    created_at timestamp(6) without time zone,
    message character varying(255),
    seen_at timestamp(6) without time zone,
    sent_at timestamp(6) without time zone,
    status smallint,
    user_id character varying(255),
    CONSTRAINT notifications_channel_check CHECK (((channel >= 0) AND (channel <= 3))),
    CONSTRAINT notifications_status_check CHECK (((status >= 0) AND (status <= 3)))
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    expires_at timestamp(6) without time zone,
    token character varying(255),
    is_used boolean NOT NULL,
    is_valid boolean NOT NULL,
    user_id bigint
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.properties (
    id character varying(255) NOT NULL,
    capacity integer NOT NULL,
    daily_price double precision NOT NULL,
    deposit_amount double precision DEFAULT 0.0 NOT NULL,
    description character varying(255) NOT NULL,
    discount_fifteen_days integer,
    discount_five_days integer,
    discount_one_month integer,
    negotiation_percentage double precision NOT NULL,
    number_of_bathrooms integer DEFAULT 1 NOT NULL,
    number_of_bedrooms integer DEFAULT 1 NOT NULL,
    number_of_beds integer DEFAULT 1 NOT NULL,
    price double precision NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    user_id character varying(255),
    address_id bigint,
    type_id bigint,
    address character varying(255),
    bathrooms integer,
    bedrooms integer,
    city character varying(120),
    country character varying(120),
    latitude double precision,
    longitude double precision,
    max_negotiation_percent integer,
    CONSTRAINT properties_status_check CHECK (((status)::text = ANY ((ARRAY['HIDDEN'::character varying, 'PENDING_DELETE'::character varying, 'VISIBLE_ONLY_FOR_TENANTS'::character varying, 'DRAFT'::character varying, 'WAITING_FOR_UPDATE'::character varying, 'DISAPPROVED'::character varying, 'PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: properties_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.properties_amenities (
    property_id character varying(255) NOT NULL,
    amenity_id bigint NOT NULL
);


--
-- Name: property_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_images (
    id bigint NOT NULL,
    is_cover boolean DEFAULT false,
    url character varying(255),
    propety_id character varying(255)
);


--
-- Name: property_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.property_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_types (
    id bigint NOT NULL,
    type character varying(255) NOT NULL
);


--
-- Name: property_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.property_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reclamation_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reclamation_attachments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer,
    file_name character varying(255),
    file_path character varying(500) NOT NULL,
    file_size bigint,
    mime_type character varying(100),
    reclamation_id bigint NOT NULL
);


--
-- Name: reclamation_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reclamation_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reclamation_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reclamations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reclamations (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    complainant_id bigint NOT NULL,
    complainant_role character varying(10) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    penalty_points integer,
    refund_amount numeric(10,2),
    resolution_notes text,
    resolved_at timestamp(6) without time zone,
    severity character varying(20),
    status character varying(20) NOT NULL,
    target_user_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT reclamations_complainant_role_check CHECK (((complainant_role)::text = ANY ((ARRAY['GUEST'::character varying, 'HOST'::character varying])::text[]))),
    CONSTRAINT reclamations_severity_check CHECK (((severity)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT reclamations_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_REVIEW'::character varying, 'RESOLVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT reclamations_type_check CHECK (((type)::text = ANY ((ARRAY['ACCESS_ISSUE'::character varying, 'NOT_AS_DESCRIBED'::character varying, 'CLEANLINESS'::character varying, 'SAFETY_HEALTH'::character varying, 'PROPERTY_DAMAGE'::character varying, 'EXTRA_CLEANING'::character varying, 'HOUSE_RULE_VIOLATION'::character varying, 'UNAUTHORIZED_GUESTS_OR_STAY'::character varying])::text[])))
);


--
-- Name: reclamations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reclamations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reclamations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suspensions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suspensions (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason character varying(255),
    property_id character varying(255)
);


--
-- Name: suspensions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suspensions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suspensions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    booking_id bigint,
    created_at timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    tx_hash text,
    user_id bigint NOT NULL,
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profile_status (
    user_id character varying(255) NOT NULL,
    is_complete boolean,
    is_deleted boolean DEFAULT false
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    birthday date NOT NULL,
    email character varying(255) NOT NULL,
    is_enabled boolean DEFAULT false NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number bigint NOT NULL,
    profile_picture character varying(255),
    rating double precision,
    score integer DEFAULT 100 NOT NULL,
    verification_code character varying(255),
    verification_expiration timestamp(6) without time zone,
    wallet_address character varying(255),
    is_suspended boolean DEFAULT false NOT NULL,
    penalty_points integer DEFAULT 0 NOT NULL,
    personal_id character varying(80),
    suspension_reason text,
    suspension_until timestamp(6) without time zone,
    full_name character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_roles (
    user_id bigint NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_roles_role_check CHECK (((role)::text = ANY ((ARRAY['TENANT'::character varying, 'HOST'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: verification_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    response character varying(255),
    status character varying(255),
    property_id character varying(255),
    CONSTRAINT verification_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: verification_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: amenities amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amenities
    ADD CONSTRAINT amenities_pkey PRIMARY KEY (id);


--
-- Name: amenity_categories amenity_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amenity_categories
    ADD CONSTRAINT amenity_categories_pkey PRIMARY KEY (id);


--
-- Name: availabilities availabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availabilities
    ADD CONSTRAINT availabilities_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: notification_logs notification_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_logs
    ADD CONSTRAINT notification_logs_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: properties_amenities properties_amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties_amenities
    ADD CONSTRAINT properties_amenities_pkey PRIMARY KEY (property_id, amenity_id);


--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- Name: property_images property_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_images
    ADD CONSTRAINT property_images_pkey PRIMARY KEY (id);


--
-- Name: property_types property_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_types
    ADD CONSTRAINT property_types_pkey PRIMARY KEY (id);


--
-- Name: reclamation_attachments reclamation_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reclamation_attachments
    ADD CONSTRAINT reclamation_attachments_pkey PRIMARY KEY (id);


--
-- Name: reclamations reclamations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reclamations
    ADD CONSTRAINT reclamations_pkey PRIMARY KEY (id);


--
-- Name: suspensions suspensions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspensions
    ADD CONSTRAINT suspensions_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: addresses uk56i7a0bfovyuekkyclkichebt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT uk56i7a0bfovyuekkyclkichebt UNIQUE (property_id);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: properties ukp6thrqusi0garmb8xys0w7fs8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT ukp6thrqusi0garmb8xys0w7fs8 UNIQUE (address_id);


--
-- Name: user_profile_status user_profile_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profile_status
    ADD CONSTRAINT user_profile_status_pkey PRIMARY KEY (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role);


--
-- Name: verification_requests verification_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_requests
    ADD CONSTRAINT verification_requests_pkey PRIMARY KEY (id);


--
-- Name: users_roles fk2o0jvgh89lemvvo17cbqvdxaa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: availabilities fk3njfsygw4mixplrtt1eqgqnl7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availabilities
    ADD CONSTRAINT fk3njfsygw4mixplrtt1eqgqnl7 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: properties fk5v48s51t6h9855i65h6opqhxo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT fk5v48s51t6h9855i65h6opqhxo FOREIGN KEY (type_id) REFERENCES public.property_types(id);


--
-- Name: properties_amenities fk8udcycu0tcgyi6p0twmdg7gip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties_amenities
    ADD CONSTRAINT fk8udcycu0tcgyi6p0twmdg7gip FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: property_images fk9q4gyvemgkqqqrp4030d9ec18; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_images
    ADD CONSTRAINT fk9q4gyvemgkqqqrp4030d9ec18 FOREIGN KEY (propety_id) REFERENCES public.properties(id);


--
-- Name: properties fka14pem3vquh6umb7s5jmb81hh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT fka14pem3vquh6umb7s5jmb81hh FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: addresses fkendfg5yr8glt92t5yc7w1vffq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fkendfg5yr8glt92t5yc7w1vffq FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: verification_requests fkllr8je3toh0ofssh53tog9ma7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_requests
    ADD CONSTRAINT fkllr8je3toh0ofssh53tog9ma7 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: notification_logs fknc1gydajjr1axlduw0ttn7nc9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_logs
    ADD CONSTRAINT fknc1gydajjr1axlduw0ttn7nc9 FOREIGN KEY (notification_id) REFERENCES public.notifications(id);


--
-- Name: properties_amenities fkoj0sm7cwu35cwnw3k7ahbukdk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties_amenities
    ADD CONSTRAINT fkoj0sm7cwu35cwnw3k7ahbukdk FOREIGN KEY (amenity_id) REFERENCES public.amenities(id);


--
-- Name: suspensions fks84ow9p8prnoc8qjdldnbg1ft; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suspensions
    ADD CONSTRAINT fks84ow9p8prnoc8qjdldnbg1ft FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: amenities fksob2wu814yc8lmh838bqvm46; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amenities
    ADD CONSTRAINT fksob2wu814yc8lmh838bqvm46 FOREIGN KEY (category_id) REFERENCES public.amenity_categories(id);


--
-- PostgreSQL database dump complete
--

\unrestrict LU7chLBYmqEboSvJvFvELmVoou81fjQCBJa0UgLu51b1Qr5xpqC11LWZWmqAOQC

