apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: derent
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: derent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 321421555934.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://d2ukdap3e0lir5.cloudfront.net"
            - name: NEXT_PUBLIC_GATEWAY_URL
              value: "https://d2ukdap3e0lir5.cloudfront.net"
            - name: NEXT_PUBLIC_USE_GATEWAY
              value: "true"
            - name: AI_API_URL
              value: "https://d2ukdap3e0lir5.cloudfront.net"
            # HTTPS endpoint for MetaMask (Cloudflare Tunnel)
            # NOTE: For production, replace with your own HTTPS endpoint
            - name: NEXT_PUBLIC_BLOCKCHAIN_RPC_URL
              value: "https://d1f19dpygrw2di.cloudfront.net"

